/**
 * Builds src/lib/world-path.ts from a Natural Earth 110m land GeoJSON.
 * Equirectangular projection into a 1000×500 box, cropped to lat 84…-58,
 * coordinates rounded to one decimal, tiny polygons dropped.
 * Usage: node scripts/world.mjs path/to/ne_110m_land.geojson
 */
import { readFileSync, writeFileSync } from 'node:fs';
const src = process.argv[2];
const gj = JSON.parse(readFileSync(src, 'utf8'));
const W = 1000, H = 500, LAT_MAX = 84, LAT_MIN = -58;
const px = (lng) => ((lng + 180) / 360) * W;
const py = (lat) => ((LAT_MAX - lat) / (LAT_MAX - LAT_MIN)) * H * (180 / (LAT_MAX - LAT_MIN)) * ((LAT_MAX - LAT_MIN) / 180);
const proj = ([lng, lat]) => [px(lng), py(lat)];
let d = '';
const ring = (coords) => {
  const pts = coords.map(proj).map(([x, y]) => [Math.round(x * 10) / 10, Math.round(y * 10) / 10]);
  // drop consecutive duplicates
  const out = [];
  for (const p of pts) { const l = out[out.length - 1]; if (!l || l[0] !== p[0] || l[1] !== p[1]) out.push(p); }
  if (out.length < 4) return '';
  // rough area filter
  let a = 0; for (let i = 0; i < out.length; i++) { const [x1, y1] = out[i], [x2, y2] = out[(i + 1) % out.length]; a += x1 * y2 - x2 * y1; }
  if (Math.abs(a / 2) < 6) return '';
  return 'M' + out.map((p, i) => (i ? 'L' : '') + p[0] + ' ' + p[1]).join('') + 'Z';
};
for (const f of gj.features) {
  const g = f.geometry;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  for (const poly of polys) d += ring(poly[0]);
}
// Antarctica removal: anything entirely below lat -58 is already cropped by py; guard by y > H
const ts = `/* Generated by scripts/world.mjs from Natural Earth 110m land (public domain). Do not edit by hand. */\nexport const WORLD_W = ${W};\nexport const WORLD_H = ${H};\nexport const WORLD_PATH = ${JSON.stringify(d)};\n`;
writeFileSync('src/lib/world-path.ts', ts);
console.log('world path bytes:', d.length);
